/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Lifeline.module.css";

function Lifeline() {
  return (
    <section className={styles.lifelineSection}>
      <h2 className={styles.title}>The Lifeline</h2>
      <p className={styles.description}>
        Call or text 24/7 for a free, confidential conversation with a trained
        counselor.
        <br />
        Call or text <span className={styles.phoneNumber}>988</span>
      </p>
    </section>
  );
}

export default Lifeline;
