/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MusicComponent.module.css";

const Footer = () => {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.footerColumn}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b766d8c1db6941812ca4c0b1f236410d71a385909e7e4360b96e481580c05f45?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
            alt="Footer logo"
            className={styles.footerLogo}
          />
        </div>
        <div className={styles.footerColumn2}>
          <div className={styles.footerLinks}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a24befe2c936dcf7a03df2611356da13da787e20bbd972c7b852edf1f93cd9ed?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
              alt="Footer link image"
              className={styles.footerImage1}
            />
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/1765409b310a3e75b8a8dbdd1affbb2e376306e67826cd00fcd173de425e45ce?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
              alt="Footer icon"
              className={styles.footerImage2}
            />
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
