/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MusicComponent.module.css";

const Header = () => {
  const navItems = [
    "Home",
    "Survey Test",
    "Health & Wellness",
    "Therapy",
    "Blogs",
  ];

  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>MindBliss</h1>
      <nav className={styles.navMenu}>
        {navItems.map((item, index) => (
          <a key={index} href="#" className={styles.navItem}>
            {item}
          </a>
        ))}
      </nav>
      <div className={styles.actionButtons}>
        <button className={styles.signInButton}>Sign in</button>
        <button className={styles.sosButton}>SOS</button>
      </div>
    </header>
  );
};

export default Header;
