/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MusicComponent.module.css";
import Header from "./Header";
import Footer from "./Footer";

const MusicComponent = () => {
  return (
    <div className={styles.musicContainer}>
      <Header />
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9504b55112e9d9e76f82c078a831b3da02b4812a1843233cc7c39bfce85a051?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
        alt="Main content illustration"
        className={styles.mainImage}
      />
      <section className={styles.contentSection}>
        <div className={styles.divider}>
          ________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
        </div>
        <div className={styles.subDivider}>__________________________</div>
        <div className={styles.textBlock}>
          _____________ <br />
          _____________ <br />
          _____________ <br />
          _____________ <br />
          _____________ <br />
          _____________ <br />
          _____________ <br />
          _____________
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default MusicComponent;
