/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreferredLanguages.module.css";

function PreferredLanguages() {
  const languages = ["English", "Hindi", "Marathi"];

  return (
    <section className={styles.preferredLanguages}>
      <h3 className={styles.title}>Preferred Languages:</h3>
      <div className={styles.languageList}>
        <div className={styles.iconContainer}>
          {languages.map((lang, index) => (
            <img
              key={index}
              src={`http://b.io/ext_${5 + index}-`}
              alt=""
              className={styles.languageIcon}
            />
          ))}
        </div>
        <ul className={styles.languages}>
          {languages.map((lang, index) => (
            <li key={index}>{lang}</li>
          ))}
        </ul>
      </div>
    </section>
  );
}

export default PreferredLanguages;
