/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SessionMode.module.css";

function SessionMode() {
  return (
    <section className={styles.sessionMode}>
      <h3 className={styles.title}>Select Mode of Session:</h3>
      <div className={styles.options}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3aae1f66ef9c7dfd7578d80afd4ae851818a4bc4a5a181ec04967761a85ca913?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
          alt=""
          className={styles.icon}
        />
        <div className={styles.modeList}>
          <p>Online (via Zoom, Skype, etc.)</p>
          <p>Offline (In-person at [Clinic Location])</p>
        </div>
      </div>
    </section>
  );
}

export default SessionMode;
