/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./TimeSlots.module.css";

function TimeSlots() {
  const availableSlots = [
    "10:00 AM - 11:00 AM",
    "2:00 PM - 3:00 PM",
    "3:00 PM - 4:00 PM",
  ];

  return (
    <section className={styles.timeSlots}>
      <h3 className={styles.title}>Available Time Slots</h3>
      <div className={styles.slotList}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/711535144e69b78d355c53feb1eadb171dfb51ae23155c5346ff6caffb245082?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
          alt=""
          className={styles.clockIcon}
        />
        <ul className={styles.slots}>
          {availableSlots.map((slot, index) => (
            <li key={index}>{slot}</li>
          ))}
        </ul>
      </div>
    </section>
  );
}

export default TimeSlots;
