/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./HealthAndWellness.module.css";
import FeatureCard from "./FeatureCard";

const HealthAndWellness = () => {
  const features = [
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b766d8c1db6941812ca4c0b1f236410d71a385909e7e4360b96e481580c05f45?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      titleUrl:"Meditation",
      //   "https://cdn.builder.io/api/v1/image/assets/TEMP/cdde1660dfa9abbcef5b029546648d8852b4dc54e0cac29d0e3231a7bfc3787a?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",

      iconUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1765409b310a3e75b8a8dbdd1affbb2e376306e67826cd00fcd173de425e45ce?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      linkTo:"/meditation"

    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/49b818871fa5f0f352aecfca6e54b1509c1ec25da0feb3c717b35a2529cc91f9?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      titleUrl:"Listen To Music",
        //"https://cdn.builder.io/api/v1/image/assets/TEMP/26fbc634dafaba2954d738d29d553877c13cf43fbc000f4a1b110f99298ac7b7?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      iconUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1765409b310a3e75b8a8dbdd1affbb2e376306e67826cd00fcd173de425e45ce?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      linkTo:"/meditation"

    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/40579cc661daa5483692f291d7d75683ebb616c1839759a8405999e929d86375?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      titleUrl:"Connect With Nature",
        // "https://cdn.builder.io/api/v1/image/assets/TEMP/7374a1938f7eb284d00e3c48800a79188cc13d164618cf9958c6ad03b3bde02e?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      iconUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1765409b310a3e75b8a8dbdd1affbb2e376306e67826cd00fcd173de425e45ce?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      linkTo:"/meditation"

    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/91c0cc68cde24636f791c8fc54a5977c7c740e987a041f2d2a69da53ffa8a7ae?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      titleUrl:"Yoga",
        //"https://cdn.builder.io/api/v1/image/assets/TEMP/0e0ad7a94746cb1403c312935c01c9145ee9a57f329a9e8049f4e2765984eac8?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      iconUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1765409b310a3e75b8a8dbdd1affbb2e376306e67826cd00fcd173de425e45ce?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b",
      linkTo:"/meditation"

    },
  ];

  return (
    <main className={styles.container}>
     
      <section>
        {features.map((feature, index) => (
          <FeatureCard key={index} {...feature} />
        ))}
      </section>
    </main>
  );
};

export default HealthAndWellness;
