/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  const navItems = [
    "Home",
    "Survey Test",
    "Health & Wellness",
    "Therapy",
    "Blogs",
  ];

  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>MindBliss</h1>
      <nav className={styles.navigation}>
        <ul className={styles.navList}>
          {navItems.map((item, index) => (
            <li key={index} className={styles.navItem}>
              <a href="#" className={styles.navLink}>
                {item}
              </a>
            </li>
          ))}
        </ul>
      </nav>
      <div className={styles.actions}>
        <button className={styles.signIn}>Sign in</button>
        <button className={styles.sos}>SOS</button>
      </div>
    </header>
  );
}

export default Header;
