/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import MeditationContent from "./MeditationContent";
import Footer from "./Footer";
import styles from "./MeditationPage.module.css";

function MeditationPage() {
  return (
    <main className={styles.meditationPage}>
   
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c13ac5cb058c80f747faac167a062c481c7edc57a71dd4f750238fa5da47c66?placeholderIfAbsent=true&apiKey=0dbd44754ffd40a6baeb24a9377e8a7b"
        alt="Meditation illustration"
        className={styles.meditationImage}
      />
      <MeditationContent />
      <Footer />
    </main>
  );
}

export default MeditationPage;
