/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MeditationContent.module.css";

function MeditationContent() {
  const meditationSteps = [
    "Find a Quiet Space",
    "Get Comfortable",
    "Close Your Eyes",
    "Focus on Your Breath",
    "Acknowledge Your Thoughts",
    "Use a Mantra or Visualization",
    "Be Present",
    "Set a Timer",
    "End Gently",
    "Reflect",
  ];
 
  return (
    <section className={styles.meditationContent}>
      <p className={styles.description}>
        When we meditate, we inject far-reaching and long-lasting benefits into
        our lives: We lower our stress levels, we get to know our pain, we
        connect better, we improve our focus, and we're kinder to ourselves. Let
        us walk you through the basics in our new mindful guide on how to
        meditate.
      </p>
      <h4 className={styles.stepsTitle}>Steps For Meditation</h4>
      <ol className={styles.stepsList}>
        {meditationSteps.map((step, index) => (
          <li key={index} className={styles.step}>
            {step}
          </li>
        ))}
      </ol>
    </section>
  );
}

export default MeditationContent;
