/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./EmergencyHelpline.module.css";

function EmergencyHelpline() {
  return (
    <section className={styles.emergencySection}>
      <h2 className={styles.title}>Emergency Helpline Numbers</h2>
      <div className={styles.helplineContainer}>
        <div className={styles.helplineName}>
          National Mental Health Helpline -
        </div>
        <div className={styles.helplineNumber}>1800-599-0019</div>
      </div>
      <div className={styles.suicidePreventionContainer}>
        <div className={styles.suicidePreventionText}>
          Suicide Prevention Helplines -
        </div>
        <div>022-2772 6771</div>
      </div>
    </section>
  );
}

export default EmergencyHelpline;
