/**
 * This code was generated by Builder.io.
 */
import React from "react";
// import MindBlissHeader from "./MindBlissHeader";
import HealingSection from "./HealingSection";
import styles from "./MindBlissApp.module.css";

const MindBlissApp = () => {
  return (
    <div className={styles.app}>
      {/* <MindBlissHeader /> */}
      <main className={styles.mainContent}>
        <HealingSection />
      </main>
    </div>
  );
};

export default MindBlissApp;
