/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MindBlissHeader.module.css";

const MindBlissHeader = () => {
  const navItems = [
    "Home",
    "Survey Test",
    "Health & Wellness",
    "Therapy",
    "Blogsss",
  ];

  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>MindBliss</h1>
      <nav className={styles.navigation}>
        <ul className={styles.navList}>
          {navItems.map((item, index) => (
            <li key={index} className={styles.navItem}>
              {item}
              {index === 0 && <div className={styles.activeIndicator} />}
            </li>
          ))}
        </ul>
      </nav>
      <div className={styles.actionButtons}>
        <button className={styles.signIn}>Sign in</button>
        <button className={styles.sos}>SOS</button>
      </div>
    </header>
  );
};

export default MindBlissHeader;
