/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>MindBliss</h1>
      <nav className={styles.navigation}>
        <ul className={styles.navList}>
          <li>
            <a href="#home">Home</a>
          </li>
          <li>
            <a href="#survey">Survey Test</a>
          </li>
          <li>
            <a href="#health">Health & Wellness</a>
          </li>
          <li className={styles.active}>
            <a href="#therapy">Therapy</a>
          </li>
          <li>
            <a href="#blogs">Blogs</a>
          </li>
        </ul>
      </nav>
      <div className={styles.actions}>
        <button className={styles.signIn}>Sign in</button>
        <button className={styles.sos}>SOS</button>
      </div>
    </header>
  );
}

export default Header;
