/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>MindBliss</h1>
      <nav className={styles.navigation}>
        <a href="/" className={styles.backLink}>
          Back to home
        </a>
        <a href="/login" className={styles.loginButton}>
          Login
        </a>
      </nav>
    </header>
  );
}

export default Header;
