/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styles from "./InputField.module.css";

function InputField({ label, type, id, showToggle }) {
  const [showPassword, setShowPassword] = useState(false);

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  return (
    <div className={styles.inputWrapper}>
      <label htmlFor={id} className={styles.label}>
        {label}
      </label>
      <input
        type={showPassword ? "text" : type}
        id={id}
        className={styles.input}
        aria-label={label}
      />
      {showToggle && (
        <button
          type="button"
          onClick={togglePasswordVisibility}
          className={styles.toggleButton}
          aria-label={showPassword ? "Hide password" : "Show password"}
        >
          {showPassword ? "Hide" : "Show"}
        </button>
      )}
    </div>
  );
}

export default InputField;