/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InputField from "./InputField";
import styles from "./RegistrationForm.module.css";

function RegistrationForm() {
  return (
    <form className={styles.registrationForm}>
      <h2 className={styles.formTitle}>Create an Account</h2>
      <InputField label="Username" type="text" id="username" />
      <InputField label="Email" type="email" id="email" />
      <InputField label="Password" type="password" id="password" showToggle />
      <button type="submit" className={styles.submitButton}>
        Create Account
      </button>
    </form>
  );
}

export default RegistrationForm;
